# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permute <- function(a, order) {
    .Call(`_NMSDE_permute`, a, order)
}

inChol2spec_c <- function(inchol, init) {
    .Call(`_NMSDE_inChol2spec_c`, inchol, init)
}

tA2G_c_cube <- function(thetas, As, init) {
    .Call(`_NMSDE_tA2G_c_cube`, thetas, As, init)
}

loglike_c_cube <- function(thetas, As, lambda, init) {
    .Call(`_NMSDE_loglike_c_cube`, thetas, As, lambda, init)
}

Workingfish_cube <- function(thetas, As, lambda, init) {
    .Call(`_NMSDE_Workingfish_cube`, thetas, As, lambda, init)
}

